_wandb:
    value:
        cli_version: 0.23.0
        e:
            d4galxd3ewhg506jm7n6jswce3ca8etd:
                codePath: kikai1\01\wandb_sample.py
                codePathLocal: wandb_sample.py
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "509722226688"
                        used: "179947892736"
                email: miu.fujita0615@gmail.com
                executable: C:\Users\miu06\vscode\project\.venv\Scripts\python.exe
                git:
                    commit: 4f015a47ca5ef488c0eccf36d5e193d7d53d79f7
                    remote: https://github.com/gnwl-aldn/project
                host: fujimiu_com
                memory:
                    total: "6162739200"
                os: Windows-11-10.0.26200-SP0
                program: C:\Users\miu06\vscode\project\kikai1\01\wandb_sample.py
                python: CPython 3.13.8
                root: C:\Users\miu06\vscode\project\kikai1\01
                startedAt: "2025-11-19T09:46:13.580240Z"
                writerId: d4galxd3ewhg506jm7n6jswce3ca8etd
        m: []
        python_version: 3.13.8
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 2
                - 13
                - 16
            "4": 3.13.8
            "5": 0.23.0
            "8":
                - 3
            "12": 0.23.0
            "13": windows-amd64
batch_size:
    value: 64
epochs:
    value: 5
learning_rate:
    value: 0.01
